CREATE TABLE "Assaults" (
    "INCIDENT_NUMBER" VARCHAR,
    "DATE_OCCURED" DATE,
    "CRIME_TYPE" VARCHAR,
    "UOR_DESC" VARCHAR,
    "TYPE_OF_ASSIGNMENT" VARCHAR,
    "TYPE_OF_ACTIVITY" VARCHAR,
    "PREMISE_TYPE" VARCHAR,
    CONSTRAINT "pk_Assaults" PRIMARY KEY (
        "INCIDENT_NUMBER"
     )
);

CREATE TABLE "Crime" (
    "INCIDENT_NUMBER" VARCHAR,
    "DATE_OCCURED" DATE,
    "UOR_DESC" VARCHAR,
    "CRIME_TYPE" VARCHAR,
    "PREMISE_TYPE" VARCHAR
);

SELECT *
FROM "Assaults"
FULL JOIN "Crime"
ON "Assaults"."INCIDENT_NUMBER" = "Crime"."INCIDENT_NUMBER";